sonar.exclusions=i18n/**/*,**/i18n/**/*,test/**/*,**/*.spec.ts,**/*.test.ts,**/*.md,**/*.yml,**/*.toml
sonar.cpd.exclusions=i18n/**/*,**/i18n/**/*,test/**/*
sonar.coverage.exclusions=i18n/**/*,**/i18n/**/*,test/**/*,**/*.spec.ts,**/*.test.ts
sonar.javascript.exclusions=i18n/**/*,**/i18n/**/*
sonar.typescript.exclusions=i18n/**/*,**/i18n/**/*
